### ISSUE TITLE
Is there any way to find out the index of the card being swiped?

### ISSUE THREAD

**Issue by barees63** [ShaunRain/flutter_tindercard#10]
Hi there,  is it possible to determine the index of the card being swiped (eg. the front card) inside the swipeUpdateCallback?  I would like to be able to change the appearance of the card as it is being swiped left or right?

**Comment by ShaunRain** [comment]
![image](https://user-images.githubusercontent.com/7543270/63081364-02785f00-bf76-11e9-81f8-132b49235290.png)

· You can get the card orientation in `swipeUpdateCallback`
· You can get the card orientation in `swipeCompleteCallback`

**Comment by barees63** [comment]
thanks!  I was looking for a way to implement a visual change on the card being swiped (eg.when swiped left it might feature a red overlay with thumbs-down icon).  I'll probably fork the lib and add a few features that are specific to the app I'm working on.  It's a nice package, thank you for making it available!
