### ISSUE TITLE
Trigger from outside

### ISSUE THREAD

**Issue by dwikresno** [ShaunRain/flutter_tindercard#15]
can you help me to make example to trigger left and right swipe from outside using cardController?

**Comment by ShaunRain** [comment]
See [https://github.com/ShaunRain/flutter_tindercard/blob/master/example/example.dart#L38](here)~

Init a CardController as param for widget, and invoke method triggerLeft/Right of your CardController to trigger swipe!

**Comment by dwikresno** [comment]
thanks :)

**Comment by shbm** [comment]
Hey @dwikresno were you able to implement it. How did you do it? I just picked up flutter just yesterday so, I don't really understand what @ShaunRain is talking about.
