### ISSUE TITLE
Getting null error while using with PageStorage widget

### ISSUE THREAD

**Issue by fannnu** [ShaunRain/flutter_tindercard#17]
Hello,

I'm getting this error: 
The method '>' was called on null.
Receiver: null
Tried calling: >(null)
User-created ancestor of the error-causing widget was:   PageStorage

I'm using Pagestorage widget for the bottom navigation bar. One of the tabs that correspond to it is intended to have this Tinder card feature.   The code used for Tindercard is the same provided in the example.

**Comment by TheFreal** [comment]
I have the same issue just using it in a MaterialApp.
`I/flutter ( 7786): The method '>' was called on null.
I/flutter ( 7786): Receiver: null
I/flutter ( 7786): Tried calling: >(null)
I/flutter ( 7786):
I/flutter ( 7786): User-created ancestor of the error-causing widget was:
I/flutter ( 7786):   MaterialApp`

**Comment by ShaunRain** [comment]
Sorry, I can not find the reason. It seems to be a flutter issue, please take a look in flutter repo.
