### ISSUE TITLE
hello friends,I want to use only  left and right swipe using TindleCardSwipe lib . Can it is possibly with lib  if you know please help me

### ISSUE THREAD

**Issue by sarbjeetromanadhaliwal** [ShaunRain/flutter_tindercard#19]

**Comment by ShaunRain** [comment]
If you mean the card will not change the vertical position when you swipe it. 
You can modify the code [here](https://github.com/ShaunRain/flutter_tindercard/blob/master/lib/flutter_tindercard.dart#L166),  remove the change of Y.
