### ISSUE TITLE
Implement function to dismiss cards

### ISSUE THREAD

**Issue by GigaDroid** [ShaunRain/flutter_tindercard#2]
Hello,
for my app it would be nice to to be able to dismiss cards by calling a function.
For example, Tinder also has buttons below the cards to swipe left and right and it's not possible to implement this feature as there is no function for this in the library at the moment.

**Comment by ShaunRain** [comment]
Got it ! 
I will add this feature as soon as possible.

**Comment by johnreyev** [comment]
Hi cool library! Any updates on this? Also, how to do undo functionality on this one?

**Comment by ShaunRain** [comment]
@GigaDroid @johnreyev  Update the [version](https://pub.dev/packages/flutter_tindercard/versions/0.1.6) for your demand ：）, please check the [sample](https://github.com/ShaunRain/flutter_tindercard/blob/master/example/example.dart) to use it!

**Comment by johnreyev** [comment]
Wow thanks @ShaunRain, can now user `triggerLeft` and `triggerRight` methods but how to do undo functionality? Or should I open another issue for this?

**Comment by ShaunRain** [comment]
@johnreyev Yes, "undo" support is different and special, better another issue ：）
