### ISSUE TITLE
How to listen that my card is being swiped right or left?

### ISSUE THREAD

**Issue by HackrHIVE** [ShaunRain/flutter_tindercard#3]
How to listen that my card is being swiped right or left?
I want to do different operations if a card is swiped right or left.
Please help me out!

**Comment by ShaunRain** [comment]
Please try the CardSwipeCompleteCallback

**Comment by HackrHIVE** [comment]
I am unable to use it properly.
No guide provided for that.
Can u give an example to use that CardSwipeCompleteCallback?
It would be helpful.
Thanks

**Comment by HackrHIVE** [comment]
Thanks , I just found it in your given example [https://github.com/ShaunRain/flutter_tindercard/blob/2700f2dd5205746519c51106bca9e744b3768e70/example/example.dart#L56](url) .

TinderSwapCard(
                swipeCompleteCallback: (CardSwipeOrientation orientation){
                  if(orientation==CardSwipeOrientation.RIGHT)
                    debugPrint('RIGHT');
                  else if(orientation==CardSwipeOrientation.LEFT)
                    debugPrint('LEFT');
                },
                swipeUpdateCallback: (DragUpdateDetails details){
                  
                },
                orientation: AmassOrientation.BOTTOM,
                totalNum: tempListIMG.length,
                stackNum: 3,
                maxWidth: MediaQuery.of(context).size.width * 0.9,
                maxHeight: MediaQuery.of(context).size.width * 0.9,
                minWidth: MediaQuery.of(context).size.width * 0.7,
                minHeight: MediaQuery.of(context).size.width * 0.7,
                cardBuilder: (context, index) => todoTemp(tempListIMG[index],tempListTEXT[index])
              )

This is the widget .
Swiping RIGHT is working fine.
But when I swipe Left , no LEFT printed in Debug Console.
It means I am not able to detect Card being swiped left.
Help me!

**Comment by anantasty** [comment]
@ShaunRain Thanks for the great library. I am having a similar issue. What is the best way to gain context on what card was swiped left or right. 
Thanks

**Comment by ShaunRain** [comment]
@HackrHIVE Which version you are using？I try the [0.1.4](https://pub.dev/packages/flutter_tindercard/versions/0.1.4) and works fine.

**Comment by ShaunRain** [comment]
@anantasty Do you mean getting a card's detail in callback when you swiping it? Like is LEFT-ING or RIGHT-ING.

**Comment by HackrHIVE** [comment]
@ShaunRain  yes I am using 0.1.4 version of ur library

**Comment by ShaunRain** [comment]
@HackrHIVE That's wired, The easy way to find reason is debug. You can debug in your callback implement to check the orientation param. If it is incorrect, debug TinderSwapCard#183 to check the value of "frontCardAlign.x".

**Comment by ShaunRain** [comment]
@HackrHIVE Here is the logic of classify the card's orientation.
![image](https://user-images.githubusercontent.com/7543270/60417403-f37e5d00-9c12-11e9-802c-8f9f6fd538a6.png)

**Comment by anantasty** [comment]
@ShaunRain I can get the left or the right in the call back but I can not tell which card was being swiped on. So if i have 18 cards i want to know if card 2 was right or left to store that information.

**Comment by HackrHIVE** [comment]
> @HackrHIVE Here is the logic of classify the card's orientation.
> ![image](https://user-images.githubusercontent.com/7543270/60417403-f37e5d00-9c12-11e9-802c-8f9f6fd538a6.png)

Thanks @ShaunRain

**Comment by HackrHIVE** [comment]
@anantasty  can u share the snippet of your use case.
It would be more helpful to figure it out.

**Comment by anantasty** [comment]
@ShaunRain i don have a code snippet to ilustrate.
The use case is
i have 15 cards. The user swipes right or left.
Currently i can tell weather the user swiped right or swiped left. Although i have no idea what card the action was taken on. 
So basically I would like to know what the index of the card was or some way to tell card that was swiped right or left.

**Comment by HackrHIVE** [comment]
`import 'package:flutter/material.dart';
import 'package:flutter_tindercard/flutter_tindercard.dart';
class SampleContent extends StatefulWidget{

  _userState createState() => _userState();

}
class _userState extends State<SampleContent>{

  List<DataHolder> array = [
    new DataHolder('Machine Learning','https://wwwadvectasse.cdn.triggerfish.cloud/uploads/2018/04/machine-learning-e1525867921119-1024x645.jpg'),
    new DataHolder('Data Structures','https://d3q6qq2zt8nhwv.cloudfront.net/course/98fc1a05763343bba4807b820c82dbd0.jpg'),
    new DataHolder('Database MS','https://seofiles.s3.amazonaws.com/seo/media/ozassignments/images/solution/07e93ffa-410e-4c77-a83d-f0b95f18ab67.png'),
    new DataHolder('Java','https://cdn-images-1.medium.com/max/1600/1*E4CO83SmCCrvRrge7U3Ahw.jpeg'),
  ];

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Scaffold(
      body: TinderSwapCard(
          swipeCompleteCallback: (CardSwipeOrientation orientation){
            if(orientation==CardSwipeOrientation.RIGHT)
              debugPrint(array[index].title+' swiped right');
            else
              debugPrint(array[index].title+' swiped left');
          },
          swipeUpdateCallback: (DragUpdateDetails details){

          },
          orientation: AmassOrientation.BOTTOM,
          totalNum: array.length,
          stackNum: 3,
          maxWidth: MediaQuery.of(context).size.width * 0.9,
          maxHeight: MediaQuery.of(context).size.width * 0.9,
          minWidth: MediaQuery.of(context).size.width * 0.7,
          minHeight: MediaQuery.of(context).size.width * 0.7,
          cardBuilder: (context, index) => createSampleCard(array[index]),
      )
    );
  }

}
class DataHolder{
  String title;
  String img;
  DataHolder(this.title,this.img);
}
class createSampleCard extends StatelessWidget{
  DataHolder obj;

  createSampleCard(this.obj);

  @override
  Widget build(BuildContext context) {
    // TODO: implement build
    return Card(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: <Widget>[
          Card(
            elevation: 10.0,
            color: Colors.black,
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(MediaQuery.of(context).size.width*0.25),),
            child: Container(
              height: MediaQuery.of(context).size.width*0.5,
              width: MediaQuery.of(context).size.width*0.5,
              decoration: BoxDecoration(
                borderRadius: BorderRadius.circular(MediaQuery.of(context).size.width*0.25),
                image: DecorationImage(image: NetworkImage(obj.img),fit: BoxFit.cover)
              ),
            ),
          ),
          SizedBox(
            height: MediaQuery.of(context).size.width*0.05,
          ),
          Text(
            obj.title,
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold
            ),
          )
        ],
      )
    );
  }
}`

**Comment by HackrHIVE** [comment]
[see sample here @anantasty ](https://github.com/HackrHIVE/HandsUp/blob/master/lib/sample)

however , I can not access my array's element in swipeCompleteCallback at [this line](https://github.com/HackrHIVE/HandsUp/blob/3a29dd1e68c5226c0e4539869912282650bf606e/lib/sample#L24)

@ShaunRain look into this.

**Comment by ShaunRain** [comment]
@HackrHIVE Can you debug your code here to check the value of "orientation"?

**Comment by ShaunRain** [comment]
@anantasty I just update the [version](https://pub.dev/packages/flutter_tindercard/versions/0.1.5) for your demand ：）, please try!

**Comment by ShaunRain** [comment]
@anantasty You can get index in "swipeCompleteCallback" now.

**Comment by anantasty** [comment]
Amazing. I really appreciate your response and quick work. Thanks

**Comment by HackrHIVE** [comment]
@anantasty Appreciate it, brother.
Can u explain, how can we access now the index?
