### ISSUE TITLE
Releasing latest stable version at pub.dev?

### ISSUE THREAD

**Issue by mechelon** [ShaunRain/flutter_tindercard#40]
Hi there,

first of all: Nice package, I really like using it!

Nevertheless, the Code here at GitHub seems to be another than the version 0.1.8 published at pub.dev, so you cannot use the new improvements e.g. the vertical swiping.

Are there plans in the near future to release the latest stable version to pub.dev?

Thanks in advance & have a nice day!

**Comment by ShaunRain** [comment]
Done : )
