### ISSUE TITLE
SwipeUp/SwipeDown Animation for following card is not smooth

### ISSUE THREAD

**Issue by mechelon** [ShaunRain/flutter_tindercard#42]
Swiping left and right works just fine, the following card gets smoothly a bit bigger and comes to the "foreground".
If I swipe up or down, the following card gets to the foreground as well - so the basic functionality is ok! - but there is no smooth transition.

Hard to explain, here is a short clip:

![tindercard_swipe_animation_error](https://user-images.githubusercontent.com/26432041/88462620-05314300-cead-11ea-8d2f-b46fedba216d.gif)

Fresh flutter project, integrated the package v0.1.9 with the sample code from the readme.

Any idea how to fix this? I would do it myself but I am not so deep in the package code (yet).

**Comment by rsaf** [comment]
I'm facing the same issue. Swapping the cards after a SwipeUp lags.

**Comment by rsaf** [comment]
@mechelon did you manage to get a fix for this?

**Comment by mechelon** [comment]
@rsaf Yeah I think so.

@ShaunRain If everything is OK with my fix, could you merge it and release the latest changes to pub.dev? Thank you :)
