### ISSUE TITLE
Implement left and right animation methods

### ISSUE THREAD

**Issue by RomanSoviak** [ShaunRain/flutter_tindercard#5]
Add methods, which emulate left and right swipe.

**Comment by ShaunRain** [comment]
If you mean calling a method to tigger swipe? [Here](https://github.com/ShaunRain/flutter_tindercard/blob/master/example/example.dart#L38) is it.

**Comment by RomanSoviak** [comment]
@ShaunRain Thanks for answer. I forgot set listener for swiping. Could you please add demonstration how `swipeLeft()`and `swipeRight()` work to existing example?

**Comment by ShaunRain** [comment]
I just update the [README](https://github.com/ShaunRain/flutter_tindercard/blob/master/README.md), please check it :)

**Comment by RomanSoviak** [comment]
@ShaunRain thanks!
