### ISSUE TITLE
Methods for controlling animation angle

### ISSUE THREAD

**Issue by RomanSoviak** [ShaunRain/flutter_tindercard#7]
Hi devs! Thanks for awesome library! 
I have issue: after triggering method `_cardController.triggerRight()` or `_cardController.triggerLeft()` 
the card moving only on X coordinate. How to make moving composed with X coordinate and angle like on that picture 
![Screenshot_7](https://user-images.githubusercontent.com/26696190/62048940-c6739900-b216-11e9-9675-82fa22c3dd21.png)

**Comment by ShaunRain** [comment]
Try the new version bro. I adjust the angle when trigger : )

**Comment by RomanSoviak** [comment]
Thanks! Nice update!
