### ISSUE TITLE
How can I catch the moment when card will be swipped?

### ISSUE THREAD

**Issue by RomanSoviak** [ShaunRain/flutter_tindercard#8]
Hi devs! I want to determine moment when tindercard will be swipped. When I move card to left on 20px and untouch my finger the card go to initial place. When I move card to left on 60px card animatedly swipped to left. How can I determine when card will be swipped. I want that to implement this feature to app
![Screenshot_9](https://user-images.githubusercontent.com/26696190/62124430-db156700-b2d2-11e9-88de-0cdb9c7370c4.png) 
 And when I swipe to right. Right button should be outlined.

**Comment by RomanSoviak** [comment]
@ShaunRain Any feedback?

**Comment by ShaunRain** [comment]
@RomanSoviak Working on it :)

**Comment by ShaunRain** [comment]
@RomanSoviak Check the new version and example, two feature added :)

**Comment by RomanSoviak** [comment]
@ShaunRain Awesome fix! Thanks a lot.
